config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: 'admin/sessions'
}
  
  devise_for :users, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: 'public' do
   get '/about', to: "homes#about"
  end
  
  scope module: 'public' do
   root to: "post_movies#index"
   resources :post_movies do
       resource :favorites, only: [:create, :destroy]
   end
  end
  
  scope module: 'public' do
    get '/users/mypage', to: "users#show"
    get '/users/information/edit', to: "users#edit"
    patch '/users/information', to: "users#update"
    get '/users/unsubscribe', to: "users#unsubscribe"
    patch '/users/withdraw', to: "users#withdraw"
  end
  
  scope module: 'public' do
   resources :post_comments, only: [:create, :destroy]
  end
  
  scope module: 'public' do
   get '/relationships/following', to: "relationships#following"
   get '/relationships/follower', to: "relationships#follower"
   resources :relationships, only: [:create, :destroy]
  end
  
  namespace :admin do
   root  "homes#top"
  end

  namespace :admin do
    resources :post_movies, only: [:index, :show, :destroy]
  end
  
  namespace :admin do
    resources :situations, only: [:new, :index, :edit, :update, :create]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/models/situation.rb
class Situation < ApplicationRecord
    
   has_many :post_movies
    
end

app/controllers/admin/situations_controller.rb
class Admin::SituationsController < ApplicationController
 def new
  @situation = Situation.new
 end
 
 def index
  @situations = Situation.all
  @situation = Situation.new
 end
 
 def create
  @situation = Situation.new(situation_params)
  @situation.save
  redirect_to admin_situations_path
 end
 
 def edit
  @situation = Situation.find(params[:id])
 end

 def update
  @situation = Situation.find(params[:id])
    
    if  @situation.update(situation_params)
        redirect_to admin_situations_path
        flash[:notice] = "シチュエーションが更新されました。"
    else
        render :edit
    end
 end
 
 private
  
 def situation_params
    params.require(:situation).permit(:name)
 end
 
end

app/helpers/admin/situations_helper.rb
module Admin::SituationsHelper
end

app/views/admin/situations/edit.html.erb
<%= form_with model: @situation, url: admin_situation_path(@situation.id), method: :patch do |f| %>
シチュエーション

<%= f.text_field :situation_type %>


<%= f.submit '変更を保存', class: 'btn btn-success' %>

  
<% end %>

app/views/admin/situations/index.html.erb
<%= form_with model: @situation, url: admin_situations_path, method: :post do |f| %>
<%= f.label :name, "シチュエーション" %>
<%= f.text_field :name %>
<%= f.submit '追加する', class: 'btn btn-success' %>
<% end %>



<table>
 <thead>
   <tr>
    <th>シチュエーション</th>
    <th></th>
   </tr>
 </thead>
<% @situations.each do |situation| %>
<tbody>
 <tr>
  <td><%= situation.name %></td>
  <td><%= link_to "編集する", edit_admin_situation_path(situation.id), class:"btn btn-success" %></td>
</tr>
</tbody>    
<% end %>
</table>
 