config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: 'admin/sessions'
}
  
  devise_for :users, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: 'public' do
   get '/about', to: "homes#about"
  end
  
  scope module: 'public' do
   root to: "post_movies#index"
   resources :post_movies do
       resource :favorites, only: [:create, :destroy]
   end
  end
  
  scope module: 'public' do
    get '/users/mypage', to: "users#show"
    get '/users/information/edit', to: "users#edit"
    patch '/users/information', to: "users#update"
    get '/users/unsubscribe', to: "users#unsubscribe"
    patch '/users/withdraw', to: "users#withdraw"
  end
  
  scope module: 'public' do
   resources :post_comments, only: [:create, :destroy]
  end
  
  scope module: 'public' do
   get '/relationships/following', to: "relationships#following"
   get '/relationships/follower', to: "relationships#follower"
   resources :relationships, only: [:create, :destroy]
  end
  
  namespace :admin do
   root  "homes#top"
  end

  namespace :admin do
    resources :post_movies, only: [:index, :show, :destroy]
  end
  
  namespace :admin do
    resources :situations, only: [:new, :index, :edit, :update, :create]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :post_movies, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  has_one_attached :profile_image
         
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
      user.user_name = 'ゲスト'
      user.introduction = '自己紹介'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
     
  def index
    # @users = User.page(params[:page]).per(10)
    @users = User.find(params[:id])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
        @user = User.find(params[:id])
    
    if  @user.update(user_params)
        redirect_to admin_user_path(@user.id)
        flash[:notice] = "会員情報が更新されました。"
    else
        render :edit
    end
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :kana_name, :user_name,:introduction,:is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>

会員ID
<%= @user.id %>


名前
<%= f.text_field :name, class:"form-control col-6" %>

ふりがな
<%= f.text_field :kana_name, class:"form-control col-6" %>


ユーザー名
<%= f.text_field :user_name, class:"form-control" %>


メールアドレス
<%= f.text_field :email, class:"form-control" %>


会員ステータス
<%= f.radio_button :is_deleted, 'false' %>
<%= f.label :is_deleted, '有効', value: false %>
<%= f.radio_button :is_deleted, 'true' %>
<%= f.label :is_deleted, '退会', value: true %>


<%= f.submit '変更内容を保存',class:"btn btn-success" %>


<% end %>

app/views/admin/users/index.html.erb
<div class="container">
        <table class="table col-10 mx-auto">
            <thead class="thead-light">
                <tr>
                 <th>ユーザーID</th>
                 <th>名前</th>
                 <th>ユーザー名</th>
                 <th>メールアドレス</th>
                 <th>会員ステータス</th>
                </tr>
            </thead>
        
            <tbody>
                <% @users.each do |user| %>
                <tr>
                  <td><%= user.id %></td>
                  <td><u><%= link_to "#{user.name}", admin_user_path(user.id), class: "text" %></u></td>
                  <td><%= user.user_name %></td>
                  <td><%= user.email %></td>
                  <% if user.is_deleted %>
                　<td><span class="text-muted">退会</span></td>
                  <% else %>
                　<td><span class="text-success">有効</span></td>
                  <% end %>
                </tr>
                <% end %>
            </tbody>
        </table>
        
    </div>
    
    <div class="container text-align-center">
    <%= paginate @users %>
    </div>

app/views/admin/users/show.html.erb
会員ID

<%= @user.id %>


名前
<%= @user.name %>

ふりがな
<%= @user.kana_name %>

ユーザー名
<%= @user.user_name %>

メールアドレス
<%= @user.email %>


会員ステータス
<% if @user.is_deleted %>
退会
<% else %>
有効
<% end %>


<%= link_to "編集する", edit_admin_user_path(@user.id), class:"btn btn-success mr-3" %>
<%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-primary" %>

</div>