config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: 'admin/sessions'
}
  
  devise_for :users, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: 'public' do
   get '/about', to: "homes#about"
  end
  
  scope module: 'public' do
   root to: "post_movies#index"
   resources :post_movies do
       resource :favorites, only: [:create, :destroy]
   end
  end
  
  scope module: 'public' do
    get '/users/mypage', to: "users#show"
    get '/users/information/edit', to: "users#edit"
    patch '/users/information', to: "users#update"
    get '/users/unsubscribe', to: "users#unsubscribe"
    patch '/users/withdraw', to: "users#withdraw"
  end
  
  scope module: 'public' do
   resources :post_comments, only: [:create, :destroy]
  end
  
  scope module: 'public' do
   get '/relationships/following', to: "relationships#following"
   get '/relationships/follower', to: "relationships#follower"
   resources :relationships, only: [:create, :destroy]
  end
  
  namespace :admin do
   root  "homes#top"
  end

  namespace :admin do
    resources :post_movies, only: [:index, :show, :destroy]
  end
  
  namespace :admin do
    resources :situations, only: [:new, :index, :edit, :update, :create]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :post_movie
end

app/models/post_movie.rb
class PostMovie < ApplicationRecord
    belongs_to :user
    belongs_to :situation
    has_many :post_comments
    has_many :favorites, dependent: :destroy
    
    enum site: { netflix: 0, amazon: 1, une: 2, hulu: 3, dvd: 4 }
    
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/situation.rb
class Situation < ApplicationRecord
    
   has_many :post_movies
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :post_movies, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  has_one_attached :profile_image
         
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
      user.user_name = 'ゲスト'
      user.introduction = '自己紹介'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    
 def top
    @post_movies = PostMovie.all
 end
 
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :configure_sign_in_params, if: :devise_controller?

  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/admin/situations_controller.rb
class Admin::SituationsController < ApplicationController
 def new
  @situation = Situation.new
 end
 
 def index
  @situations = Situation.all
  @situation = Situation.new
 end
 
 def create
  @situation = Situation.new(situation_params)
  @situation.save
  redirect_to admin_situations_path
 end
 
 def edit
  @situation = Situation.find(params[:id])
 end

 def update
  @situation = Situation.find(params[:id])
    
    if  @situation.update(situation_params)
        redirect_to admin_situations_path
        flash[:notice] = "シチュエーションが更新されました。"
    else
        render :edit
    end
 end
 
 private
  
 def situation_params
    params.require(:situation).permit(:name)
 end
 
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
     
  def index
    # @users = User.page(params[:page]).per(10)
    @users = User.find(params[:id])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
        @user = User.find(params[:id])
    
    if  @user.update(user_params)
        redirect_to admin_user_path(@user.id)
        flash[:notice] = "会員情報が更新されました。"
    else
        render :edit
    end
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :kana_name, :user_name,:introduction,:is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_movies_helper.rb
module Admin::PostMoviesHelper
end

app/helpers/admin/situations_helper.rb
module Admin::SituationsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>movieich</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
  <script src="https://kit.fontawesome.com/1871c9c7c6.js" crossorigin="anonymous"></script>

<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mx-auto">
              
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", users_mypage_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿しよう', new_post_movie_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '映画を探そう', posts_path, class: 'nav-link text-dark' %>
            </li>
             <li class="nav-item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_users_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", admin_post_movies_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "シチュエーション一覧", admin_situations_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            
            <% else %>
            <li class="nav-item">
              <%= link_to "movieichとは?", about_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "会員登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ゲストログイン(閲覧用)", users_guest_sign_in_path, method: :post, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
    <div class="text-dark"><%= flash[:notice] %></div>
    <%= yield %>
    </main>
  
  </body>
  
</html>